services:
  bot:
    image: "bot"
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uv", "run", "main.py"]
    
    env_file:
      - ".env"
    depends_on:
      pg_main:
        condition: service_healthy
  pg_main:
    image: postgres
    container_name: pg_main
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${APP_CONFIG__DB__POSTGRES_DB}
      POSTGRES_USER: ${APP_CONFIG__DB__POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    command: postgres -c listen_addresses='*'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
